// Emits CSS custom properties scoped to [data-theme][data-regime], flattening every
// token category into bare semantic names (--ground, --ui, --radius, ...). Components
// consume semantics only. Adding a theme/regime here re-renders the shell with zero
// component edits (brief §7, acceptance item 2). Run: `pnpm --filter @wrizo/tokens build`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Regime, TokenCategory, Tokens } from "./types";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const tokens = JSON.parse(readFileSync(resolve(root, "tokens.json"), "utf8")) as Tokens;

function flatten(regime: Regime): string {
  const categories: TokenCategory[] = [regime.color, regime.type, regime.geometry, regime.motion];
  const lines: string[] = [];
  for (const category of categories) {
    for (const [key, value] of Object.entries(category)) {
      lines.push(`  --${key}: ${value};`);
    }
  }
  return lines.join("\n");
}

const blocks: string[] = [];
let count = 0;
for (const [theme, regimes] of Object.entries(tokens.theme)) {
  for (const [regime, values] of Object.entries(regimes)) {
    blocks.push(`[data-theme="${theme}"][data-regime="${regime}"] {\n${flatten(values)}\n}`);
    count += 1;
  }
}

const css =
  "/* GENERATED by @wrizo/tokens — do not edit by hand. Source of truth: tokens.json */\n" +
  blocks.join("\n\n") +
  "\n";

mkdirSync(resolve(root, "dist"), { recursive: true });
writeFileSync(resolve(root, "dist", "tokens.css"), css, "utf8");
console.log(`@wrizo/tokens: emitted dist/tokens.css (${count} theme x regime set(s))`);
